### PR TITLE
Adductor (foam roll) Update

### PR DESCRIPTION
**Pull request by BoraHurst**

### CODE REVIEW

**Review by GregoryConrad — CHANGES_REQUESTED** [review]
I wouldn't say this exercise is a variation on anything. It is pretty standalone

**Comment by BoraHurst** [comment]
Really? its a foam roll excercise so I would say its a foam roll variation?

idk

**Comment by GregoryConrad** [comment]
foam roll is the equipment used. An exercise variation itself in this context would be an "adductor stretch" or something similar, but that wouldn't make sense here.

**Comment by GregoryConrad** [comment]
Another important point: variations should be irrespective of the equipment used.

**Review by BoraHurst — COMMENTED** [review]
updated this

**Comment by BoraHurst** [comment]
Thanks for the clarification, will keep that in mind in future patches.

**Review by GregoryConrad — APPROVED** [review]

**Pull request merged**
